    1. Create and Inspect an Array
        Create a 1D NumPy array containing integers from 10 to 50 (inclusive) with a step of 5.

        Print its shape, size, and data type.

    2. Generate a Matrix with Random Values
        Generate a 4x5 NumPy array with random integers between 1 and 100.

        Find the maximum and minimum values, along with their indices.

    3. Reshape an Array
        Create a 1D array of numbers from 1 to 24, then reshape it into a 4x6 matrix.

        Extract the 2nd row and 3rd column.

    4. Boolean Indexing
        Given a NumPy array of 15 random integers between 0 and 50, find all elements greater than 25 and replace them with -1.

    5. Mathematical Operations
        Create two 1D NumPy arrays:
        a = [1, 2, 3, 4, 5] and b = [10, 20, 30, 40, 50]

        Perform element-wise addition, subtraction, multiplication, and division.

    6. Statistical Computations
        Generate a 5x5 matrix with random floats between 0 and 1.

        Compute the mean, median, variance, and standard deviation.

    7. Matrix Multiplication
        Create two matrices:

        A is 3x2 with values from 1 to 6.

        B is 2x3 with values from 7 to 12.
        Perform matrix multiplication (A @ B) and display the result.

    8. Slice and Modify
        Create a 6x6 array of integers from 1 to 36.

        Extract the 3x3 sub-matrix from the center and set all its values to 0.

    9. Use of np.where
        Create a NumPy array with values [5, 10, 15, 20, 25].

        Replace all elements greater than 15 with 99, otherwise replace with 0.

    10. Broadcasting Example
        Create a 4x4 array filled with 10s.

        Subtract a 1D array [0, 1, 2, 3] from each row using NumPy broadcasting.


In [1]:
import numpy as np

# 1
array_1d = np.arange(10, 51, 5)

print("Array:", array_1d)
print("Shape:", array_1d.shape)
print("Size:", array_1d.size)
print("Data type:", array_1d.dtype)

1D Array: [10 15 20 25 30 35 40 45 50]
Shape of 1D array: (9,)
Size of 1D array: 9
Data type of 1D array: int64


In [2]:
# 2. Generate a Matrix with Random Values
matrix_4x5 = np.random.randint(1, 101, size=(4, 5))
print("\n4x5 Matrix with random values:\n", matrix_4x5)

max_value = np.max(matrix_4x5)
min_value = np.min(matrix_4x5)
max_index = np.argmax(matrix_4x5)
min_index = np.argmin(matrix_4x5)

print("Maximum value:", max_value)
print("Minimum value:", min_value)
print("Index of maximum value (flattened):", max_index)
print("Index of minimum value (flattened):", min_index)

# using unravel_index here...
max_2d_index = np.unravel_index(max_index, matrix_4x5.shape)
min_2d_index = np.unravel_index(min_index, matrix_4x5.shape)

print("Index of maximum value 2d", max_2d_index)
print("Index of minimum value", min_2d_index)


4x5 Matrix with random values:
 [[97 76 93 23 97]
 [56 26 41 91 59]
 [39 97 62 27 96]
 [86 75 83 57 49]]
Maximum value: 97
Minimum value: 23
Index of maximum value (flattened): 0
Index of minimum value (flattened): 3
Index of maximum value (2D): (np.int64(0), np.int64(0))
Index of minimum value (2D): (np.int64(0), np.int64(3))


In [3]:
# Given a NumPy array of 15 random integers between 0 and 50, find all elements greater than 25 and replace them with -1.
random_array = np.random.randint(0, 51, 15)
print("Original array:", random_array)

random_array[random_array > 25] = -1
print("Array after boolean indexing:", random_array)


Original array: [ 0  7 13 19  2  1 27  4  3 40 42 38 45 29  3]
Array after boolean indexing: [ 0  7 13 19  2  1 -1  4  3 -1 -1 -1 -1 -1  3]


In [4]:
# Create two 1D NumPy arrays:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("Array a:", a)
print("Array b:", b)

#element-wise addition, subtraction, multiplication, and division.
addition = a + b
subtraction = a - b


multiplication = a * b
division = a / b

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)


Array a: [1 2 3 4 5]
Array b: [10 20 30 40 50]

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [5]:
# 6
# a 5x5 matrix with random floats between 0 and 1.
matrix = np.random.rand(5, 5)
print(matrix)

# Compute the mean, median, variance, and standard deviation.
mean_value = np.mean(matrix)
median_value = np.median(matrix)
variance_value = np.var(matrix)
std_dev_value = np.std(matrix)

print("Mean:", mean_value)
print("Median:", median_value)
print("Variance:", variance_value)
print("Standard deviation:", std_dev_value)


5x5 matrix with random floats:
 [[0.78240188 0.69458922 0.53613163 0.49930174 0.54624286]
 [0.5713717  0.94349887 0.26607906 0.16647927 0.63663436]
 [0.1295494  0.3941628  0.12178335 0.14140588 0.96267913]
 [0.25381222 0.37177964 0.48455483 0.8731183  0.4436656 ]
 [0.59570281 0.13526172 0.59151596 0.16861231 0.5114778 ]]

Mean: 0.47287249431007644
Median: 0.49930174338091105
Variance: 0.06413650264111821
Standard deviation: 0.253251856145455


In [6]:
# 7
# A is 3x2 with values from 1 to 6.
A = np.arange(1, 7).reshape(3, 2)
print("\nMatrix A (3x2):", A)

# B is 2x3 with values from 7 to 12.
B = np.arange(7, 13).reshape(2, 3)
print("\nMatrix B (2x3):", B)

#matrix multiplication (A @ B)
matrix_product = A @ B
print("\nMatrix product (A @ B):", matrix_product)


Matrix A (3x2):
 [[1 2]
 [3 4]
 [5 6]]

Matrix B (2x3):
 [[ 7  8  9]
 [10 11 12]]

Matrix product (A @ B):
 [[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


In [7]:
# 8
array_6x6 = np.arange(1, 37).reshape(6, 6)
print("Original 6x6 array:", array_6x6)

array_6x6[1:4, 1:4] = 0
print("after modification:", array_6x6)


Original 6x6 array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Array after modifying the center sub-matrix:
 [[ 1  2  3  4  5  6]
 [ 7  0  0  0 11 12]
 [13  0  0  0 17 18]
 [19  0  0  0 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [8]:
# 9 np.where
array_where = np.array([5, 10, 15, 20, 25])
print("Original array for np.where:", array_where)

modified_array_where = np.where(array_where > 15, 99, 0)
print("Array after using np.where:", modified_array_where)


Original array for np.where: [ 5 10 15 20 25]
Array after using np.where: [ 0  0  0 99 99]


In [9]:
# 10. Broadcasting
array_4x4 = np.full((4, 4), 10)
print("original 4x4 array:", array_4x4)

subtraction_array = np.array([0, 1, 2, 3])
broadcasted_result = array_4x4 - subtraction_array
print("after broadcasting", broadcasted_result)


Original 4x4 array:
 [[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]

Array after broadcasting subtraction:
 [[10  9  8  7]
 [10  9  8  7]
 [10  9  8  7]
 [10  9  8  7]]
